-- MySQL Script generated by MySQL Workbench
-- Thu Oct 22 18:47:01 2015
-- Model: shoppingdb    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shoppingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoppingdb` DEFAULT CHARACTER SET latin1 ;
-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `shoppingdb`;

-- -----------------------------------------------------
-- Table `shoppingdb`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`Employee` (
  `EmployeeID` INT(11) NOT NULL AUTO_INCREMENT,
  `EmployeeName` VARCHAR(200) NOT NULL,
  `CreatedBy` INT(11),
  `CreationDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `LastUpdatedBy`  INT(11),
  `LastUpdatedDate` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`EmployeeID`))
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
