-- MySQL Script generated by MySQL Workbench
-- Thu Oct 22 18:47:01 2015
-- Model: shoppingdb    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema shoppingdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `shoppingdb` DEFAULT CHARACTER SET latin1 ;

-- -----------------------------------------------------
-- Schema new_schema1
-- -----------------------------------------------------
USE `shoppingdb`;

-- -----------------------------------------------------
-- Table `shoppingdb`.`EmpHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `shoppingdb`.`EmployeeHistory` (
  `EmpHistoryID` INT NOT NULL AUTO_INCREMENT,
  `VersionNumber` INT NOT NULL,
  `EmpName` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`EmpHistoryID`)
) ENGINE = InnoDB;

-- -----------------------------------------------------
-- TRIGGER `shoppingdb`.`TRIG_EMP_INSERT`
-- -----------------------------------------------------
DROP TRIGGER IF EXISTS `shoppingdb`.`TRIG_EMP_INSERT`;

DELIMITER $$

CREATE TRIGGER `shoppingdb`.`TRIG_EMP_INSERT` 
  AFTER INSERT ON `shoppingdb`.`Employee`
  FOR EACH ROW 
BEGIN 
  INSERT INTO `shoppingdb`.`EmployeeHistory` (`VersionNumber`,`EmployeeID`,`EmployeeName`,`CreatedBy`,`CreationDate`,`LastUpdatedBy`,`LastUpdatedDate`)
  VALUES(1,NEW.EmployeeID,NEW.EmployeeName,NEW.CreatedBy,NEW.CreationDate,NEW.LastUpdatedBy,NEW.LastUpdatedDate);

END$$
DELIMITER ;

-- -----------------------------------------------------
-- TRIGGER `shoppingdb`.`TRIG_EMP_UPDATE`
-- -----------------------------------------------------
DROP TRIGGER IF EXISTS `shoppingdb`.`TRIG_EMP_UPDATE`;

DELIMITER $$

CREATE TRIGGER `shoppingdb`.`TRIG_EMP_UPDATE` 
  AFTER UPDATE ON `shoppingdb`.`Employee`
  FOR EACH ROW 
BEGIN
  SET @VersionNumber = (SELECT COALESCE(MAX(VersionNumber),0)+1 FROM `shoppingdb`.`EmployeeHistory` where EmployeeID = NEW.EmployeeID);
  INSERT INTO `shoppingdb`.`EmployeeHistory` (`VersionNumber`,`EmployeeID`,`EmployeeName`,`CreatedBy`,`CreationDate`,`LastUpdatedBy`,`LastUpdatedDate`)
  VALUES(@VersionNumber,NEW.EmployeeID,NEW.EmployeeName,NEW.CreatedBy,NEW.CreationDate,NEW.LastUpdatedBy,NEW.LastUpdatedDate);

END$$
DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
